name: Build and Deploy Blazor App

on:
  push:
    branches:
       Developement  # Change to your development branch if needed

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0 
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Change if using a different .NET version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Blazor App
        run: dotnet publish -c Release -o output  # Ensure it's published to the './publish' folder

      - name: Copy _nojekyll to publish directory
        run: |
          if [ -f "./nojekyll" ]; then
            cp ./nojekyll ./publish/  # Copy _nojekyll to the publish directory
          else
            echo "_nojekyll file not found"
          fi

      - name: Checkout or Create WeatherBuild Branch
        run: |
          git fetch origin
          git checkout WeatherBuild || git checkout -b WeatherBuild

      - name: Clean the build-output branch
        run: |
          git rm -rf .

      - name: Copy build files to the branch
        run: |
          cp -r output/wwwroot/* .

      - name: Commit and Push Build to the build-output branch
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Deploy built Blazor app"
          git push origin WeatherBuild --force
      - name: Clean up and show build files only
        run: |
          git rm -rf "Blazor Weather App"
          git rm -rf "output"
          git commit -m "Delete dummy output"
          git push origin WeatherBuild --force
